### ISSUE TITLE
False negatives and typo in documentation

### ISSUE THREAD

**Issue by alejandroeclair** [mozilla/fxa-common-password-list#14]
Hello,

I did the following on your code and I was getting false positives:
`
> const commonPassworList = require('fxa-common-password-list');
undefined
> commonPassworList.test('password');
true
> commonPassworList.test('@!#^GDSAQ@#^Q#@^$YAESFDAS');
false
> commonPassworList.test('g00dPa$$w0rD');
false
`

I checked the txt file and `g00dPa$$w0rD` is a "weak" and predictable password, so why is it giving me a false?
<img width="222" alt="Screen Shot 2019-11-26 at 2 53 10 pm" src="https://user-images.githubusercontent.com/52657230/69598140-83a6be00-105c-11ea-9981-868fb7ffd907.png">

Additionally, in your "usage" documentation, you're defining `commonPassworList`  without the D in  password and then in example `commonPasswordList.test('@!#^GDSAQ@#^Q#@^$YAESFDAS');` you put the D.

Thanks

**Comment by alejandroeclair** [comment]
I now understand how your system works... You have to generate a new "encodedpassword" with new passwords? Then what's the point of including the 10M password txt file in the repo if your source doesn't use it?

**Comment by shane-tomlinson** [comment]
> Then what's the point of including the 10M password txt file in the repo if your source doesn't use it?

Hi @alejandroeclair - it's included so we can generate new lists of different sizes when needed, which we just did within the last few months.

**Comment by alejandroeclair** [comment]
Hi @shane-tomlinson , if I wanted to include your entire file on my checks, how would I go about that? I'd like it that the solution to always be reading from a single source of truth. I know that 1m or 10m records is a lot, but chopping it down to 50000 is a huge difference compared to a full list of 1 million.

Thank you

**Comment by shane-tomlinson** [comment]
> I know that 1m or 10m records is a lot, but chopping it down to 50000 is a huge difference compared to a full list of 1 million.

The thing is password usage isn't distributed evenly, usage of the top N passwords far exceeds even those in the range of [N + 1, 2*N). Past a certain point adding a password to the list has diminishing returns and becomes just additional bytes that must be shipped to every user. Sure, attackers won't be able to rainbow table your password database as easily, but proper salting and hashing also mitigate this. And if the threat model is an online only attack, rate limiting login requests is very effective at mitigating dictionary attacks.

Also remember that this is a dictionary that has to be sent to your user's devices, 50k passwords already requires 242KB which can be prohibitive to mobile users far from a mobile phone tower, or where bandwidth is at a premium. 1M entries requires 2.8MB, and all 10M requires 8.5MB, both of which are simply too big for mass use.

Directions for how to extract a new list [are found here](https://github.com/mozilla/fxa-common-password-list#generating-password-list).
