### ISSUE TITLE
False positive rate is quite high

### ISSUE THREAD

**Issue by no-man-is-an-island** [mozilla/fxa-common-password-list#5]
Firstly - thanks for the library! I couldn't find a common password library for node that's being actively maintained.

If I have my maths right (and experimentally it seems to be about right), setting the number of bits to 10 times the number of passwords in the bloom filter will result in a false positive rate of just under 1% given you're using 8 hashes. This feels a little high for the use case of password strength checking - quite a lot of strong passwords will be rejected seemingly inexplicably. 

Would you be open to increasing the value here and rebuilding the bloom filters?

https://github.com/mozilla/fxa-common-password-list/blob/master/scripts/plaintext2bloom.js#L22

(I've built my own bloom filters for my application now using your code - more just thinking for future people who come across the library)

**Comment by shane-tomlinson** [comment]
@no-man-is-an-island - Thanks for the report, and I'm glad to see the library is getting use outside of us! We have had at least one complaint with "my password isn't common at all, you can do better than this!"

The obvious thing is increasing the number of bits increases the resulting size, so there is a tradeoff to be made. Maybe I could create a table of bits and entries => size and see if there is any sort of logical sweet spot, or have the script accept a bit size as a config option and generate new bloomfilter data if needed.

**Comment by no-man-is-an-island** [comment]
I think a higher number of bits in the default data would provide a better out-of-the-box experience for people who just want to pick up the library and use it. As you say, the size of the resultant bloom filter is the trade-off -I went for 30 bits x number of passwords in the end for a top 100k bloom filter of just under 1MB. This gives us a false positive rate of 1/100,000 or so, which seems acceptable.

I also like the idea of making it configurable - with warnings about the risks of setting it too low of course :)
